//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTCPayServer.Stream.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BTCPayServer.Stream.Common.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Button_Change {
            get {
                return ResourceManager.GetString("Button_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Button_Connect {
            get {
                return ResourceManager.GetString("Button_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy URL.
        /// </summary>
        public static string Button_CopyUrl {
            get {
                return ResourceManager.GetString("Button_CopyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Button_Disconnect {
            get {
                return ResourceManager.GetString("Button_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Button_Register {
            get {
                return ResourceManager.GetString("Button_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string Button_SelectFile {
            get {
                return ResourceManager.GetString("Button_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Button_Send {
            get {
                return ResourceManager.GetString("Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send test alert.
        /// </summary>
        public static string Button_SendTestAlert {
            get {
                return ResourceManager.GetString("Button_SendTestAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Label_Amount {
            get {
                return ResourceManager.GetString("Label_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your BTCPay Server Store ID.
        /// </summary>
        public static string Label_BTCPayServerStoreId {
            get {
                return ResourceManager.GetString("Label_BTCPayServerStoreId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your BTCPay Server URL.
        /// </summary>
        public static string Label_BTCPayServerUrl {
            get {
                return ResourceManager.GetString("Label_BTCPayServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string Label_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string Label_ConfirmPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string Label_CurrentPassword {
            get {
                return ResourceManager.GetString("Label_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default language.
        /// </summary>
        public static string Label_DefaultCulture {
            get {
                return ResourceManager.GetString("Label_DefaultCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default currency.
        /// </summary>
        public static string Label_DefaultCurrency {
            get {
                return ResourceManager.GetString("Label_DefaultCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate page identifier.
        /// </summary>
        public static string Label_DonatePageIdentifier {
            get {
                return ResourceManager.GetString("Label_DonatePageIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate page stylesheet.
        /// </summary>
        public static string Label_DonatePageStylesheet {
            get {
                return ResourceManager.GetString("Label_DonatePageStylesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Analytics identifier.
        /// </summary>
        public static string Label_GtagId {
            get {
                return ResourceManager.GetString("Label_GtagId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string Label_NewPassword {
            get {
                return ResourceManager.GetString("Label_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate page logo.
        /// </summary>
        public static string Label_PageLogo {
            get {
                return ResourceManager.GetString("Label_PageLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate page title.
        /// </summary>
        public static string Label_PageTitle {
            get {
                return ResourceManager.GetString("Label_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message.
        /// </summary>
        public static string Label_YourMessage {
            get {
                return ResourceManager.GetString("Label_YourMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string Label_YourName {
            get {
                return ResourceManager.GetString("Label_YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        public static string Languages_Options_Czech {
            get {
                return ResourceManager.GetString("Languages_Options_Czech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Languages_Options_English {
            get {
                return ResourceManager.GetString("Languages_Options_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access user identity..
        /// </summary>
        public static string Message_CannotAccessUserIdentity {
            get {
                return ResourceManager.GetString("Message_CannotAccessUserIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot finish user registration.
        /// </summary>
        public static string Message_CannotFinishUserRegistration {
            get {
                return ResourceManager.GetString("Message_CannotFinishUserRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot send tip yet..
        /// </summary>
        public static string Message_CannotSendTipYet {
            get {
                return ResourceManager.GetString("Message_CannotSendTipYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No payment gateway connected..
        /// </summary>
        public static string Message_NoPaymentGateway {
            get {
                return ResourceManager.GetString("Message_NoPaymentGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page not found.
        /// </summary>
        public static string Message_PageNotFound {
            get {
                return ResourceManager.GetString("Message_PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send tip to.
        /// </summary>
        public static string Message_SendTipTo {
            get {
                return ResourceManager.GetString("Message_SendTipTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string Message_SomethingWentWrong {
            get {
                return ResourceManager.GetString("Message_SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test donate has been successfully queued..
        /// </summary>
        public static string Message_TestDonateQueued {
            get {
                return ResourceManager.GetString("Message_TestDonateQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for the tip.
        /// </summary>
        public static string Message_ThankYouForTip {
            get {
                return ResourceManager.GetString("Message_ThankYouForTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged as.
        /// </summary>
        public static string Message_YouAreLoggedAs {
            get {
                return ResourceManager.GetString("Message_YouAreLoggedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to disconnect {0}?.
        /// </summary>
        public static string Question_ReallyDisconnect_Pattern {
            get {
                return ResourceManager.GetString("Question_ReallyDisconnect_Pattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to specific BTCPay Server store, which will be used as payment processor..
        /// </summary>
        public static string Text_BTCPay {
            get {
                return ResourceManager.GetString("Text_BTCPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public page to tip..
        /// </summary>
        public static string Text_DonationPage {
            get {
                return ResourceManager.GetString("Text_DonationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To the Streamlabs will be published donation alert received from BTCPay Server..
        /// </summary>
        public static string Text_Streamlabs {
            get {
                return ResourceManager.GetString("Text_Streamlabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Streamlabs integration by publishing the test alert without any payment..
        /// </summary>
        public static string Text_TestDonation {
            get {
                return ResourceManager.GetString("Text_TestDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgment.
        /// </summary>
        public static string Title_Acknowledgment {
            get {
                return ResourceManager.GetString("Title_Acknowledgment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BTCPay Server connection.
        /// </summary>
        public static string Title_BTCPayServerConnection {
            get {
                return ResourceManager.GetString("Title_BTCPayServerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string Title_ChangePassword {
            get {
                return ResourceManager.GetString("Title_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customization.
        /// </summary>
        public static string Title_Customization {
            get {
                return ResourceManager.GetString("Title_Customization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Title_Dashboard {
            get {
                return ResourceManager.GetString("Title_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Title_Donate {
            get {
                return ResourceManager.GetString("Title_Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donation page.
        /// </summary>
        public static string Title_DonationPage {
            get {
                return ResourceManager.GetString("Title_DonationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Title_Error {
            get {
                return ResourceManager.GetString("Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Title_Logout {
            get {
                return ResourceManager.GetString("Title_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Title_Profile {
            get {
                return ResourceManager.GetString("Title_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Title_Register {
            get {
                return ResourceManager.GetString("Title_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Title_Settings {
            get {
                return ResourceManager.GetString("Title_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Title_SignIn {
            get {
                return ResourceManager.GetString("Title_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streamlabs connection.
        /// </summary>
        public static string Title_StreamlabsConnection {
            get {
                return ResourceManager.GetString("Title_StreamlabsConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test donation.
        /// </summary>
        public static string Title_TestDonation {
            get {
                return ResourceManager.GetString("Title_TestDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name may only be letters, numbers, spaces and underscores between 2-25 characters.
        /// </summary>
        public static string Validation_DonatorRegularExpressionMatch {
            get {
                return ResourceManager.GetString("Validation_DonatorRegularExpressionMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only alphanumeric characters and _ (underscore) are allowed.
        /// </summary>
        public static string Validation_IdentifierRegularExpressionMatch {
            get {
                return ResourceManager.GetString("Validation_IdentifierRegularExpressionMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format.
        /// </summary>
        public static string Validation_Invalid_Format {
            get {
                return ResourceManager.GetString("Validation_Invalid_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format..
        /// </summary>
        public static string Validation_InvalidFileType {
            get {
                return ResourceManager.GetString("Validation_InvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        public static string Validation_InvalidPassword {
            get {
                return ResourceManager.GetString("Validation_InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format of the URL.
        /// </summary>
        public static string Validation_InvalidUrl {
            get {
                return ResourceManager.GetString("Validation_InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string Validation_InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("Validation_InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length exceeded (230 characters).
        /// </summary>
        public static string Validation_MaxLength_230 {
            get {
                return ResourceManager.GetString("Validation_MaxLength_230", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length exceeded (25 characters).
        /// </summary>
        public static string Validation_MaxLength_25 {
            get {
                return ResourceManager.GetString("Validation_MaxLength_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length is 2 characters.
        /// </summary>
        public static string Validation_MinLength_2 {
            get {
                return ResourceManager.GetString("Validation_MinLength_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min tip is {0} {1}.
        /// </summary>
        public static string Validation_MinTip_Format {
            get {
                return ResourceManager.GetString("Validation_MinTip_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password do not match.
        /// </summary>
        public static string Validation_PasswordDontMatch {
            get {
                return ResourceManager.GetString("Validation_PasswordDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown target user.
        /// </summary>
        public static string Validation_UnknownTargetUser {
            get {
                return ResourceManager.GetString("Validation_UnknownTargetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used identifier yet.
        /// </summary>
        public static string Validation_UsedIdentifier {
            get {
                return ResourceManager.GetString("Validation_UsedIdentifier", resourceCulture);
            }
        }
    }
}
